alias: Blinds — Reopen All After Sunset
description: ""
triggers:
  - entity_id: sun.sun
    attribute: elevation
    below: -1
    trigger: numeric_state
conditions:
  - condition: template
    value_template: "{{ now().month >= 4 and now().month <= 10 }}"
  - condition: state
    entity_id: input_boolean.blinds_manual_override
    state: "off"
  - condition: template
    value_template: "{{ now().hour >= 18 }}"
actions:
  - target:
      entity_id:
        - cover.piano_shades_all_homekit
        - cover.office_shades_all_homekit
        - cover.entry_blinds_homekit
        - cover.living_room_shades_all_homekit
        - cover.kitchen_shades_all_homekit
    action: cover.open_cover
mode: single
