alias: Xcel Peak — Begin Float (5pm)
description: ""
triggers:
  - at: "17:00:00"
    trigger: time
conditions:
  - condition: state
    entity_id: input_boolean.hvac_killswitch
    state: "off"
  - condition: template
    value_template: "{{ now().month >= 5 and now().month <= 9 }}"
  - condition: template
    value_template: >
      {{ states('climate.honeywell_t_stat_main_floor') == 'cool'  or
      states('climate.honeywell_t_stat_main_floor') == 'fan_only' }}
    alias: Only run if A/C is in cooling or fan mode, not heating
actions:
  - target:
      entity_id: climate.honeywell_t_stat_main_floor
    data:
      temperature: 79
    action: climate.set_temperature
  - target:
      entity_id: climate.honeywell_t_stat_upstairs
    data:
      temperature: 80
    action: climate.set_temperature
  - data:
      title: ⚡ Peak hours — A/C on standby
      message: >
        5pm peak window started. Setpoints raised to 79/80°F. Solar is selling
        back at 3x rate until 9pm.
    action: notify.send_message
    target:
      entity_id: notify.pixel_9_pro
mode: single
